baseURL: "https://albertobinetti.github.io" 
title: Alberto Binetti
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Working papers
          url: papers/
          weight: 1
        - name: Work in progress
          url: workinprogress/
          weight: 2


params:
    description: "Hi! I am an incoming Ph.D. student in economics at Princeton. I am interested (for now) in topics in political and behavioral economics. From Naples."
    author: Alberto Binetti
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: "<span style='color: #000080;'>Alberto Binetti</span>"
          subtitle: "Hi! I am an incoming Ph.D. student in economics at <a href='https://economics.princeton.edu' style='color: #000080; font-weight: bold;'>Princeton</a>. I received both my Bachelor's and my Master's from <a href='https://www.unibocconi.it/it/node/1' style='color: #000080; font-weight: bold;'>Bocconi</a>.
          <br>
          I am interested (for now) in topics in political and behavioral economics. From Naples.
          <br>
          You can find my CV <a href='cv.pdf' style='color: #000080; font-weight: bold;'>here</a>."
          imageUrl: "headshot.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Alberto Binetti
          buttons:
            - name: Working papers
              url: papers/
            - name: Work in progress
              url: workinprogress/

    socialIcons:
        - name: Email
          url: mailto:abinetti@princeton.edu
        - name: CV
          url: cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=zUWmT7oAAAAJ&hl=en&oi=ao
        - name: Twitter
          url: https://twitter.com/Al_Bi99

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Alberto Binetti"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2